### ISSUE TITLE
can you support find xss in href?

### ISSUE THREAD

**Issue by wilson9x1** [stamparm/DSXS#6]
can you support find xss in href?

egg:
```
<?php
$input= str_replace("\"", "&quot;" ,$_GET['xss']);
$input=str_replace(">","&lt;",$input);
$input=str_replace("<","&gt;",$input);
echo '<a href="';
print($input);
echo '">click<a/>';
?>
````
http://127.0.0.1/2.php?xss=javascript:alert(1)  when click it will has xss vuls。

but DSXS can't find this。

**Comment by stamparm** [comment]
Can't implement because of one simple reason. If you take a look into payloads being sent, you'll see that they look "inconspicuous". This project has been used as part of one larger (prototype) project where the original idea has been to send as less non-offensive looking payloads.
