### ISSUE TITLE
question about REGULAR_PATTERNS

### ISSUE THREAD

**Issue by mounsurf** [stamparm/DSXS#7]
for example, when using  `<!--[^>]*%abc|abc[^<]*-->` to search `<!-- abc--> xxxabc-->`
, this regex can capture the last `abc-->` , but `abc-->` is not in comment.

**Comment by stamparm** [comment]
So, basically, you are searching for cases with least probability where those regexes will fail? I can find lots of more cases, but not sure what's the point.

One question. Have you ever found any web page with response like `<!-- abc--> xxxabc-->` ? If answer is no, I am not sure what's the point of this issue
