### ISSUE TITLE
Merge with XSStrike

### ISSUE THREAD

**Issue by shadowzoom** [stamparm/DSXS#9]
Hi Miroslav @stamparm, it would be great if you can join to developers of https://github.com/s0md3v/XSStrike
It use some code of sqlmap and will be great if xsstrike will be develop amazing pro coder like you

**Comment by stamparm** [comment]
@shadowzoom Hi. Thank you for your call. Currently I am in work with other projects over my head. Hence, I'll have to turn your call down :(
